#!/usr/bin/env python3

import os
import json
import pathlib
import subprocess
import click

SNAP = pathlib.Path(os.getenv("SNAP") or "/snap/microk8s/current")
HELM = SNAP / "microk8s-helm3.wrapper"
KUBECTL = SNAP / "microk8s-kubectl.wrapper"

@click.command()
@click.option('--delete-all-crds', is_flag=True)
def main(
    delete_all_crds: bool,
):
    click.echo("Disabling AMD GPU operator")
    stdout = subprocess.check_output([HELM, "uninstall", "amd-gpu-operator", "-n", "kube-amd-gpu"])

    if delete_all_crds:
        click.echo("WARNING: Attempting to delete all CRDs")
        try:
            crds_json_string = subprocess.check_output([KUBECTL, "get", "crds", "-o", "json"])
            crds = json.loads(crds_json_string)
            for crd in crds:
                crd_name = crd.get("name")
                subprocess.run([KUBECTL, "delete", "crds", crd_name])
        except (OSError, json.JSONDecodeError):
            click.echo("ERROR: Failed to retrieve all CRDs, only removing default CRDs", err=True)

if __name__ == "__main__":
    main()
    

